/*
 * SPDX-FileCopyrightText: 2024 Roland Rusch, easy-smart solution GmbH <roland.rusch@easy-smart.ch>
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef LIBSMART_STM32NETXHTTPWEBCLIENT_LIBSMART_CONFIG_DIST_HPP
#define LIBSMART_STM32NETXHTTPWEBCLIENT_LIBSMART_CONFIG_DIST_HPP

#include "nx_web_http_client.h"

#define LIBSMART_STM32NETXHTTPWEBCLIENT

#define LIBSMART_STM32NETXHTTPWEBCLIENT_HTTP_PORT NX_WEB_HTTP_SERVER_PORT
#define LIBSMART_STM32NETXHTTPWEBCLIENT_HTTPS_PORT NX_WEB_HTTPS_SERVER_PORT

#define LIBSMART_STM32NETXHTTPWEBCLIENT_TIMEOUT NX_WEB_HTTP_CLIENT_TIMEOUT


#endif
